[package]
name = "holodeck-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
holodeck-core = { workspace = true }
holodeck-services = { workspace = true }
tokio = { workspace = true }
ratatui = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
